### ISSUE TITLE
SyntaxError: /.babelrc: Error while parsing JSON

### ISSUE THREAD

**Issue by HashCode55** [ooade/NextSimpleStarter#36]
Hi! 

I tried to run the example mentioned in the readme but its throwing this error: 

```
{ SyntaxError: /.babelrc: Error while parsing JSON - Unexpected EOF at line 1 column 2 of the JSON5 data. Still to read: ""
    at error (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/json5/lib/json5.js:56:25)
    at word (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/json5/lib/json5.js:393:13)
    at value (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/json5/lib/json5.js:493:56)
    at Object.parse (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/json5/lib/json5.js:508:18)
    at ConfigChainBuilder.addConfig (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:150:65)
    at ConfigChainBuilder.findConfigs (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
    at buildConfigChain (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
    at findBabelConfig (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/next/dist/server/build/babel/find-config.js:25:53)
    at _callee2$ (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/next/dist/server/build/webpack.js:369:60)
    at tryCatch (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/mehulahuja/Desktop/freeways-web-2/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise.F (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/babel-runtime/node_modules/core-js/library/modules/_export.js:35:28)
    at /Users/mehulahuja/Desktop/freeways-web-2/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at createCompiler (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/next/dist/server/build/webpack.js:546:17)
    at HotReloader._callee2$ (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/next/dist/server/hot-reloader.js:224:69)
    at tryCatch (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/mehulahuja/Desktop/freeways-web-2/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise.F (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/babel-runtime/node_modules/core-js/library/modules/_export.js:35:28)
    at HotReloader.<anonymous> (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at HotReloader.start (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/next/dist/server/hot-reloader.js:253:22)
    at Server._callee$ (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/next/dist/server/index.js:157:41)
    at tryCatch (/Users/mehulahuja/Desktop/freeways-web-2/node_modules/regenerator-runtime/runtime.js:65:40)
  message: '/.babelrc: Error while parsing JSON - Unexpected EOF at line 1 column 2 of the JSON5 data. Still to read: ""',
  at: 1,
  lineNumber: 1,
  columnNumber: 2 }
```

I'm running OSX (Sierra)
Node version 6.10.3

**Comment by ooade** [comment]
Please, can i get more details cos we don't handle .babelrc file in any way. That is Next.js's Job :man_shrugging:
