### ISSUE TITLE
getInitialProps() issues

### ISSUE THREAD

**Issue by luandro** [ooade/NextSimpleStarter#9]
Trying to do simple data fetching using next's `getInitialProps`, but it's been hard to get it to work.

I believe this first error I get has to do with getting Babel configs right.

```
value: async function getInitialProps() {
                 ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at _callee$ (/user/NextSimpleStarter/node_modules/next/dist/server/require.js:33:46)
    at tryCatch (/user/NextSimpleStarter/node_modules/regenerator-runtime/runtime.js:64:40)
```

After adding `transform-runtime` the error seems to go away.
```
"plugins": [
    ["transform-runtime", {
      "polyfill": false,
      "regenerator": true
    }],
],
```

But still `getInitialProps()` doesn't get called. You can check out [my fork](https://github.com/Luandro-com/NextSimpleStarter) for code.

**Comment by ooade** [comment]
@luandro I'm so sorry about that. I totally went off next's babel configuration. I should have added "next/babel" preset but there's a way we could spin this up. I don't know if you're interested

 - Delete ProviderWrapper and remove its instance from '/utils/index.js'
 - Create a Layout or Provider Component to be more realistic (takes in children) and return it back nested within Redux's Provider

**Comment by ooade** [comment]
And Yeah, probably delete the .babelrc config it won't be needed.

**Comment by luandro** [comment]
Want a PR?

**Comment by ooade** [comment]
If you wish :100:

**Comment by luandro** [comment]
👍
